### ISSUE TITLE
Sub Scenes Don't keep Grid Size and Background Offset

### ISSUE THREAD

**Issue by MrPrimate** [ggagnon76/scene-scroller-maker#10]
This tool is super cool, but when using the "Divide into smaller subscenes" option the new scene don't keep the Grid Size or background offset from the parent scene.

**Comment by ggagnon76** [comment]
When you say the new scene doesn't keep the background offset, does that mean that the pieces are misaligned with the walls?  Could you provide photos/videos showing what you mean so I can set up a test in order to fix?

Same with the grid size.  I'm not sure it has to, or should.  But if I can visually see what you mean, it would help.

**Comment by MrPrimate** [comment]
Okay, so I may have been wrong, it might just by the Grid Size in pixels that needs copying across.

Please see:

Original:
![original](https://user-images.githubusercontent.com/3985378/193471300-bc052a85-9ae7-433c-8074-966c876c8c98.png)

Subscene:
![partial](https://user-images.githubusercontent.com/3985378/193471305-56e61df8-42ea-49a5-8122-4ea2b424f35f.png)

If I change the subscene to match the original grid size:

![fixed](https://user-images.githubusercontent.com/3985378/193471315-2a2288aa-fed9-4772-847a-3f596b1a0aea.png)

**Comment by ggagnon76** [comment]
Just released v1.5
Check to see if the grid sizing is reflected in the sub-scenes.

**Comment by MrPrimate** [comment]
Perfect! Thanks!
