### ISSUE TITLE
Image editing features do not work on remote URLs (those not hosted in the local Foundry instance)

### ISSUE THREAD

**Issue by shemetz** [ggagnon76/scene-scroller-maker#19]
see title.  For example, hosting [this file](https://file.garden/YHgdF6Mz-xKjrLIe/D%26D/Undercaper/Other%20hell%20bits/crystal_crossroads.jpeg) works, but trying to use the "scale everything in a scene" button fails with this error: 

`Target directory E:\FoundryVTT\Data\https://file.garden/YHgdF6Mz-xKjrLIe/D%26D/Undercaper/Other%20hell%20bits does not exist.`

**Comment by ggagnon76** [comment]
In this current version, it would not be possible to support remote files like this because the module saves a new image at the same location the original was found.  I doubt `file.garden` would allow me to save an image originating from Foundry.

However, in my upcoming version, I am creating a setting to set up a default save location for images.  Once that is implemented, I can take a look at fixing this issue.

**Comment by shemetz** [comment]
Agreed, I would expect it to take the remote image and save it locally in some default folder.

**Comment by ggagnon76** [comment]
This should now be resolved with release of v2.1
